os:
  - linux
dist: bionic
sudo: required
git:
  depth: false
language: python
python:
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      unrar
      tree


install:
  - python3 setup.py install

script:
 - yes n | ezsub update
 - ezsub login
 - ezsub cfg set Defaults.group True
 - ezsub cfg set Defaults.auto_select True
 - ezsub cfg set Defaults.open_after False
 - ezsub cfg set Defaults.site subscene hastisub subf2m xyz
 - ezsub cfg set Defaults.lngs en fa
 - ezsub dl -t friends first season
 - sudo apt remove unrar -y -qq > /dev/null
 - ezsub x -t friends first season
 - ezsub history run 2
 - ezsub info
 - ezsub backup -O
 - ezsub clean -t friends first season -l en --zero
 - ezsub clean -t friends first season -a
 - ezsub cfg show
 - ezsub h show

after_success:
  - cat ~/.ezsub/ezsub.log
  - tree ~/.ezsub/
